<!doctype html>
<html lang="fr">

<head>
  <meta charset="UTF-8">
  <title>Distorsion</title>
  <link rel="stylesheet" href="public/css/app.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css">


</head>

<body>
  <header>
    <div class="logo">
      <h1>Distorsion</h1><img src="assets/img/distorsion.png" alt="logo-distorsion">
    </div>
    <nav class="row">
      <a class="col-1 col-md-4" href="index.php?page=chat">Chat</a>
      <a class="col-1 col-md-4" href="index.php?page=about">À propos</a>
    </nav>
  </header>


    <?php 
      
      require $view 
    ?>
    
  </main>
  

  <footer>
    Le premier chat anonyme du monde !
  </footer>


</body>

</html>