<div class="add">
  <form method="POST">
    <?php foreach ($this->errors as $error) : ?>
      <p class="text-danger"><?= htmlspecialchars($error) ?></p>
    <?php endforeach; ?>

    <fieldset>
      <legend>Ajouter une catégorie</legend>
      <label for="name">Nom</label>
      <input type="text" name="name" id="name" value="">
    </fieldset>

    <button type="submit">Valider</button>
  </form>
</div>