<div class="text_about"><h2>Chat Anonyme PHP - Une Expérience de Communication Sécurisée</h2>

<div class="text">
Description :

Bienvenue sur notre plateforme de chat anonyme développée en PHP selon les principes de la programmation orientée objet (POO) et l'architecture MVC (Modèle-Vue-Contrôleur). Cette application offre un espace de communication sécurisé, où les utilisateurs peuvent échanger des messages en toute confidentialité.</div></div>